const appVersion = process.env.npm_package_version;
const appEnv = process.env.APP_ENV;
const ogImageUrl = `https://assets.sembark.com/images/og-image.png?v=${appVersion}`;
module.exports = {
  appEnv,
  version: appVersion,
  appName: "Sembark",
  publicUrl: process.env.APP_PUBLIC_URL,
  description:
    "Manage travel sales, reservation and accounting with Sembark and get 1-click quotation, smart calendar reservation and accounting with expense management",
  keywords: [
    "travel agency software",
    "travel agency management software",
    "Online travel agency software",
    "travel agency accounting software",
    "online travel CRM",
    "best travel software",
    "software for travel agency",
    "online accounting software travel agency",
    "billing software for travel agency",
    "tour and travel software",
    "software used in tourism industry",
    "best tour operator software",
    "travel crm software",
    "travel management software",
  ].join(","),
  lang: "en",
  locale: "en_in",
  authorName: "Sudhir Mitharwal",
  authorEmail: "sudhir@sembark.com",
  ogImageUrl,
  twitterCreator: "@sudhirmith",
  twitterUsername: "@SembarkTech",
  gaMeasurementId: process.env.APP_GA_MEASUREMENT_ID,
  facebookUrl: `https://www.facebook.com/sembarktech/`,
  twitterUrl: `https://twitter.com/SembarkTech`,
  linkedinUrl: `https://www.linkedin.com/company/sembark`,
  githubUrl: `https://www.github.com/sembark`,
  address: {
    name: "Sembark Tech. Pvt. Ltd",
    street: "Vaisali Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    zip: "302012",
    phoneDisplay: "+91-9005505374",
    phoneCall: "+919005505374",
    secondaryPhoneDisplay: "8950392425",
    secondaryPhoneCall: "+918950392425",
    email: "support@sembark.com",
    landmark: "Akshardham Temple",
    country: "India",
  },
  supportEmail: "support@sembark.com",
  legalEmail: "support@sembark.com",
  whatsappNumber: "+919621324422",
  travelProductUrl: "/travel-management-software/",
  accountRegistrationUrl: process.env.APP_ACCOUNT_REGISTRATION_URL,
  docsUrl: "https://docs.sembark.com",
};
